import Head from 'next/head';

export const getServerSideProps = () => {
  return {
    props: {}
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Semiphemeral</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello world</main>
    </>
  );
}
